### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/r2lab#1]
A request from users: being able to visualize 2d data collected on nodes

Given in input
* a set of input parameters and associated ranges; e.g.
  * sender: [1..37]
  * phy (channel): [1, 54]
  * etc..
* for each/some combination of these, we get a mapping {node -> value}; e.g.
  * sender=1, phy=54: {1:12, 2:14, ...}
  * sender=2, phy=54: {1:10, 2:8, ...}
  * ...

Given such a dataset we would like a visualisation tool, that ideally
* has widgets to set the various input parameters
* and when relevant (the chosen values indeed have a mapping) visualize the data
  * poor-man : sliders on the node
  * more advanced : some sort of heatmap; for the record Mario had developped [some visu of that sort](https://r2lab.inria.fr/stats.md) when reporting the number of mishaps with the nodes

**Comment by parmentelat** [comment]
let us be careful to use **the same colormap for all input variants**, so that visualisation does not create a misleading artifact

**Comment by turletti** [comment]
-- I'd say we need a 3D visu as we do need to plot the X value on the real position of nodes. The tool from Mario is not convenient as it is missing the information that node Y is neighbor of node Z for instance.

**Comment by turletti** [comment]
Ok. A  feature to add is the possibility to show the corresponding data value when moving the mouse on the map --Indeed, the color will not be precise enough to evaluate the differences between neighbor nodes.

**Comment by turletti** [comment]
Plotly seems a great tool for our purpose and with better rendering than matplotlib. 
You can try plotly-heatmap.py on git r2lab/demos/heatmap. 

If you look at the last  example of
https://plot.ly/python/animations/
You can add different sliders to select all the different paramaters.

Actually we need 5 sliders:

- to select the transmitter node: [1, 37]
- to select the receiving antenna in which we retrieve RSSI : [4 possibilities max according to the number of antennas used]
- to select the transmitting power [now 2 values]
- to select the number of antennas used [1,2,3]
- to select the transmitting PHY rate (now 2 values)

In the heatmap directory, there are both the scripts to get the data from R2lab and to plot them with matplotlib but such tool with sliders would be very useful to rapdly analyze impact of each parameter and anomalies. 

What is missing now is the moulinette to form the whole database based on plot-all.py and the plotly script with sliders.

**Comment by parmentelat** [comment]
Was giving this a try, but the `RSSI.txt` file is missing so I can't see what plotly-heatmap.py would give

```
parmentelat ~/git/r2lab/demos/heatmap $ ./plotly-heatmap.py
Traceback (most recent call last):
  File "./plotly-heatmap.py", line 89, in <module>
    if __name__ == "__main__":main()
  File "./plotly-heatmap.py", line 50, in main
    file_in = open("RSSI.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'RSSI.txt'
```

**Comment by parmentelat** [comment]
We now provide an example of a notebook that uses plot.ly in offline mode and that implements an interactive visualization of a data file DATA-RSSI.txt along the lines discussed above.

see https://github.com/parmentelat/r2lab/blob/public/demos/heatmap-nb/heatmap-rssi.ipynb
