### ISSUE TITLE
demos/jobs-angle-measure experiment not working with latest intelcsi images

### ISSUE THREAD

**Issue by sfehlandt** [parmentelat/r2lab#2]
Hi, i tried to execute this experiment with the latest intelcsi images in several combinations of nodes and none worked. It seemed the sender was working but the receiver was not logging results.
Then I tried using the first version (intelcsi-v1) and it worked fine.
Do you know what could be causing this? It would be great if you could update the script in order to fix this, or state that it doesn't work as a comment in the script.

**Comment by parmentelat** [comment]
fixed in ee35258d23fcf2bbc448315db488fb07b3c6c1bd

**Comment by parmentelat** [comment]
Hi Sebastian

Thanks for reporting that

We had initially planned a more thorough troubleshooting session with Naoufal - who had put together the intelcsi image in the first place - but for various reasons, so far we have not been able to get around to tackling this

hopefully we will get to the bottom of it sometime, in the meanwhile I did add a comment in the script as per your suggestion

PS.

feel free to also use the fit-r2lab-users@inria.fr if you need assistance with R2lab 

— Thierry
