### ISSUE TITLE
Plotly dependency

### ISSUE THREAD

**Issue by WalidDabbous** [parmentelat/r2lab#6]
Hi there,
I just tried to install this stuff, and it seems that it requires Plotly to be installed.
However, this is not mentioned in the dependencies.
So could you please mention it ?

thanks,

Walid

**Comment by parmentelat** [comment]
I take it when you say 'this stuff' you mean the radiomap demo

**Comment by WalidDabbous** [comment]
sorry, yes sure. it is for the radioman demo.
I find this rather cool!
